from __future__ import annotations

import json
import re
from pathlib import Path

import typer
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table

from adslot_scout.analyze import analyze_site
from adslot_scout.github_push import GitHubClient, GitHubError
from adslot_scout.report import render_markdown, write_local

load_dotenv()
app = typer.Typer(add_completion=False, help="Find high-value ad placements and keywords for a website.")
console = Console()


def slug_domain(domain: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", domain.lower()).strip("-")
    return slug or "site"


@app.command()
def analyze(
    url: str = typer.Argument(..., help="Website to audit"),
    out: Path | None = typer.Option(None, help="Local folder for REPORT.md and JSON"),
    max_pages: int = typer.Option(4, min=1, max=15, help="Same-domain pages to fetch"),
    push: bool = typer.Option(False, help="Push briefing to GitHub"),
    owner: str | None = typer.Option(None, help="GitHub user or org"),
    repo_name: str | None = typer.Option(None, help="Repository name"),
    private: bool = typer.Option(True, help="Create the repo as private"),
    create_repo: bool = typer.Option(True, help="Create the repo if it does not exist"),
    branch: str = typer.Option("main", help="Branch to commit onto"),
) -> None:
    """Audit a site, print ranked slots, and optionally publish a GitHub briefing."""
    with console.status("Fetching and scoring the site..."):
        result = analyze_site(url, max_pages=max_pages + 1)

    console.print(f"\n[bold]{result.domain}[/bold]")
    console.print(result.summary)

    table = Table(title="High-value placements")
    table.add_column("#", justify="right")
    table.add_column("Slot")
    table.add_column("Value")
    table.add_column("Score", justify="right")
    table.add_column("Devices")
    for slot in result.placements:
        table.add_row(
            str(slot.rank),
            slot.name,
            slot.estimated_value,
            str(slot.score),
            ", ".join(slot.devices),
        )
    console.print(table)

    kw = Table(title="Keywords")
    kw.add_column("Phrase")
    kw.add_column("Intent")
    kw.add_column("Source")
    kw.add_column("Score", justify="right")
    for item in result.keywords[:15]:
        kw.add_row(item.phrase, item.intent, item.source, str(item.score))
    console.print(kw)

    out_dir = out or Path("reports") / slug_domain(result.domain)
    paths = write_local(result, out_dir)
    console.print(f"Wrote local briefing to [green]{out_dir}[/green]")

    if not push:
        return

    try:
        client = GitHubClient()
        me = client.whoami()
        owner_name = owner or me.get("login")
        if not owner_name:
            raise GitHubError("Could not resolve GitHub owner.")
        repo = repo_name or f"ad-intel-{slug_domain(result.domain)}"
        remote_files = {
            "briefing/REPORT.md": paths["report"].read_text(encoding="utf-8"),
            "briefing/analysis.json": paths["analysis"].read_text(encoding="utf-8"),
            "briefing/placements.json": paths["placements"].read_text(encoding="utf-8"),
            "briefing/keywords.csv": paths["keywords"].read_text(encoding="utf-8"),
            "briefing/README.md": (
                f"# Briefing for {result.domain}\n\n"
                f"Generated by AdSlot Scout from `{result.seed_url}`.\n"
            ),
        }
        html = client.publish_briefing(
            owner=owner_name,
            repo=repo,
            files=remote_files,
            branch=branch,
            create=create_repo,
            private=private,
            description=f"Ad placement and keyword briefing for {result.domain}",
        )
        console.print(f"Pushed briefing to [bold blue]{html}[/bold blue]")
    except GitHubError as exc:
        console.print(f"[red]GitHub publish failed:[/red] {exc}")
        raise typer.Exit(code=1) from exc


@app.command("dump-json")
def dump_json(
    url: str,
    max_pages: int = typer.Option(3, min=1, max=15),
) -> None:
    """Print the raw analysis JSON."""
    result = analyze_site(url, max_pages=max_pages + 1)
    console.print_json(json.dumps(result.to_dict()))


if __name__ == "__main__":
    app()
