from __future__ import annotations

import csv
import json
from pathlib import Path

from adslot_scout.models import Analysis


def render_markdown(analysis: Analysis) -> str:
    auction = analysis.header_auction or {}
    lines = [
        f"# Ad placement briefing — {analysis.domain}",
        "",
        f"Seed URL: {analysis.seed_url}",
        "",
        analysis.summary,
        "",
        "## Layout signals",
        "",
        f"- Page type guess: `{analysis.layout.likely_page_type}`",
        f"- Content depth: `{analysis.layout.content_depth}`",
        f"- Header / nav / article / sidebar / footer: "
        f"{analysis.layout.has_header} / {analysis.layout.has_nav} / "
        f"{analysis.layout.has_article} / {analysis.layout.has_sidebar} / {analysis.layout.has_footer}",
        f"- Paragraphs / images on primary page: {analysis.layout.paragraph_count} / {analysis.layout.image_count}",
        "",
        "## Detected ad and measurement tech",
        "",
    ]
    if analysis.ad_tech:
        for hit in analysis.ad_tech:
            lines.append(f"- **{hit.name}** ({hit.category}) — `{hit.evidence}`")
    else:
        lines.append("- None detected in HTML. Ads may load after consent or via a tag manager.")

    lines += [
        "",
        "## Auction and demand graph",
        "",
        f"- Wrapper: `{auction.get('wrapper', 'unknown')}`",
        f"- Client auction detected: `{auction.get('detected', False)}`",
        f"- Adapters / bidder orgs: {', '.join(auction.get('bidder_orgs') or []) or 'none'}",
        f"- Timeout hint: {auction.get('timeout_ms') or 'n/a'}",
        "",
    ]
    for note in auction.get("notes") or []:
        lines.append(f"- {note}")
    for note in analysis.sharing_notes:
        lines.append(f"- {note}")

    lines += ["", "## Parties on the page", ""]
    if analysis.parties:
        for party in analysis.parties:
            lines.append(f"- **{party['org']}** ({party['role']}) via `{party['host']}`")
    else:
        lines.append("- No mapped demand / tracker hosts in the HTML.")

    lines += ["", "## Client identifier matching", ""]
    if analysis.cookie_syncs:
        for ev in analysis.cookie_syncs:
            lines.append(
                f"- `{ev.get('dest_org') or ev.get('dest_host')}` via {ev.get('kind')} `{ev.get('param')}`"
            )
        lines.append(
            "- Client matches are a lower bound. Partners that never touch the browser will not appear here."
        )
    else:
        lines.append("- No sync pixels/paths in the fetched HTML.")

    lines += ["", "## Ranked high-value placements", ""]
    for slot in analysis.placements:
        lines += [
            f"### {slot.rank}. {slot.name} — {slot.estimated_value} (score {slot.score})",
            "",
            f"- Fit: {slot.fit}",
            f"- Devices: {', '.join(slot.devices)}",
            f"- Formats: {', '.join(slot.formats)}",
            f"- Viewability: {slot.viewability}",
            f"- Where: {slot.where}",
            f"- Why it pays: {slot.why}",
            f"- How to implement: {slot.implementation}",
            f"- Watch-outs: {slot.caveats}",
            "",
        ]
    lines += ["## Keywords to load into the media kit / campaigns", ""]
    lines.append("| Phrase | Intent | Source | Score |")
    lines.append("| --- | --- | --- | --- |")
    for kw in analysis.keywords:
        lines.append(f"| {kw.phrase} | {kw.intent} | {kw.source} | {kw.score} |")
    lines += ["", "## Pages crawled", ""]
    for page in analysis.pages:
        status = page.error or page.status
        lines.append(f"- {page.url} — {status} — {page.word_count} words — {page.title}")
    lines += [
        "",
        "---",
        "Generated by [AdSlot Scout](https://github.com/code4johnm/adslot-scout). "
        "Placement scores are layout heuristics. Bid-influence needs a collected auction log.",
        "",
    ]
    return "\n".join(lines)


def write_local(analysis: Analysis, out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {
        "report": out_dir / "REPORT.md",
        "analysis": out_dir / "analysis.json",
        "placements": out_dir / "placements.json",
        "keywords": out_dir / "keywords.csv",
        "parties": out_dir / "parties.json",
        "syncs": out_dir / "cookie_syncs.json",
    }
    paths["report"].write_text(render_markdown(analysis), encoding="utf-8")
    paths["analysis"].write_text(json.dumps(analysis.to_dict(), indent=2), encoding="utf-8")
    paths["placements"].write_text(
        json.dumps([p.to_dict() for p in analysis.placements], indent=2), encoding="utf-8"
    )
    paths["parties"].write_text(json.dumps(analysis.parties, indent=2), encoding="utf-8")
    paths["syncs"].write_text(json.dumps(analysis.cookie_syncs, indent=2), encoding="utf-8")
    with paths["keywords"].open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["phrase", "intent", "source", "score", "ngram"])
        writer.writeheader()
        for kw in analysis.keywords:
            writer.writerow(kw.to_dict())
    return paths
